export const LOGGED_IN = 'LOGGED_IN'
export const LOGGED_OUT = 'LOGGED_OUT'
export const LOGIN_ERROR = 'LOGIN_ERROR'
// export const WS_SEND = 'WS_SEND'
export const WS_CONNECT = 'WS_CONNECT'
// export const WS_DISCONNECT = 'WS_DISCONNECT'
export const WS_OPEN = 'WS_OPEN'
export const WS_CLOSE = 'WS_CLOSE'
export const WS_ERROR = 'WS_ERROR'
export const WS_MESSAGE = 'WS_MESSAGE'

// export const MAIN_PAGE_WEBSOCKET = 'MAIN_PAGE_WEBSOCKET'
// export const WS_CONNECTED = 'WS_CONNECTED'
// export const WS_DISCONNECTED = 'WS_DISCONNECTED'