export const LOGGED_IN = 'LOGGED_IN'
export const LOGGED_OUT = 'LOGGED_OUT'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const WS_CONNECT = 'WS_CONNECT'
export const WS_OPEN = 'WS_OPEN'
export const WS_CLOSE = 'WS_CLOSE'
export const WS_ERROR = 'WS_ERROR'
export const WS_MESSAGE = 'WS_MESSAGE'

export const SET_PHONE_TABLE_DATA = 'SET_PHONE_TABLE_DATA'
export const SET_PHONE_TABLE_ROW = 'SET_PHONE_TABLE_ROW'
export const REMOVE_PHONE_TABLE_ROW = 'REMOVE_PHONE_TABLE_ROW'
export const CREATE_PHONE_TABLE_ROW = 'CREATE_PHONE_TABLE_ROW'

export const SET_ACCOUNT_TABLE_DATA = 'SET_ACCOUNT_TABLE_DATA'
export const SET_ACCOUNT_TABLE_ROW = 'SET_ACCOUNT_TABLE_ROW'
export const REMOVE_ACCOUNT_TABLE_ROW = 'REMOVE_ACCOUNT_TABLE_ROW'
export const CREATE_ACCOUNT_TABLE_ROW = 'CREATE_ACCOUNT_TABLE_ROW'

export const SET_CROSSES_TABLE_DATA = 'SET_CROSSES_TABLE_DATA'
export const SET_CROSSES_TABLE_ROW = 'SET_CROSSES_TABLE_ROW'

export const SET_LOGS_TABLE_DATA = 'SET_LOGS_TABLE_DATA'